database:
  global:
    username: root
    password: pass
    database: db
    host: 'localhost:3306'
    prefix: ''
  server:
    username: root
    password: pass
    database: db
    host: 'localhost:3306'
    prefix: 'factions_'
commands:
  pvp: false
  inn: true
  credits: true
  gbroadcast: true
  stp: true
  server: true
cmdrewrite:
  enabled: true
  rewrite:
    credits: credits
    pvp: pvp
    gbroadcast: gbroadcast
    stp: stp
news:
  enabled: false
misc:
  color:
    sign: true
    book: false
  serverList:
  - creative
  - factions
  - minigames
  - lobby
  spawn:
    tpOnFall: false
    worlds:
    - world
    tpOnJoin: false
  maxbans:
    enabled: false
  disablePlayerColission: false
  collisionType: FOR_OWN_TEAM
pvp:
  enabled: false
  killsTable: inncore_kills
  historyTable: inncore_kills-h
  scoreboard:
    use: true
    time: 200
    delay: 6000
    players: 10
    update: 3600
loginlog:
  enabled: false
  enabledAuthLog: false
  loginTable: inncore_logins
  authTable: inncore_authentications
npc:
  enabled: false
  staffMember:
    enabled: true
    yOffset: 3.5
  permittedGroups:
  - light
  - dark
towns:
  enabled: false
  world: world
chat:
  sync:
    enabled: false
    serverName: factions
    serverPass: 123456
    connection:
      server: localhost
      port: 8756
      password: 123456
factionsmisc:
  enabled: false
  mining:
    enabled: true
    permission: inncraft.mining
    disableWorldMining: true
    mainWorld: world
    divide: false
    levelSize: 2000
    zoneTesting: true
    miningZone:
      0;0: 1
      -1;0: 2
      -1;-1: 3
      0;-1: 4
    townMiningZone:
      1: 1
      2: 1
      3: 2
      4: 3
      5: 3
      6: 3
  disableStr2Potions: true
  obsidian:
    enabled: true
    message: '&cYou can only get obsidian from the shop!'
  fixReportRtsCmd: true
  disableVillagerTrading: true
  rightClickIronDoors: true
  nerfXP: true
  removeCheatedItems: true
skyblock:
  enabled: false
  fall:
    saveInv: true
    table: inncore_fallInventories
vote:
  enabled: false
  services:
  - 'Minecraft-MP.com'
  - 'TopG.org'
  startCmd:
    - perm player {player} addgroup voter
  endCmd:
    - perm player {player} removegroup voter
  bungeeStartCmd: []
  bungeeEndCmd: []
bungee:
  enabled: false
paper:
  enabled: true
discord:
  enabled: false
